arenda/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import index
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings



from prof.views import edit_profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth.urls', namespace='auth')),
    path('profile/edit/', edit_profile, name='edit_profile'),
    path('object/', include('news.urls', namespace='object')),
    path('prof/', include('prof.urls', namespace='prof')),
    path('report/', include('report.urls', namespace='report')),
    path('main/', include('main.urls', namespace='main')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auth/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.sitemaps.views import index
from django.urls import path, reverse_lazy
from django.views.generic import CreateView

app_name = 'auth'

urlpatterns = [
    path('sign-up/', CreateView.as_view(template_name='sign-up.html',
                                        success_url=reverse_lazy('prof:prof_create'),
                                        form_class=UserCreationForm,
                                        model = User), name = 'sign-up'),
    path('sign-in/', LoginView.as_view(template_name = 'sign-in.html', next_page=reverse_lazy('object:main')), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('auth:login')), name='logout')

]

main/urls.py
from django.urls import path

from main import views


app_name = 'main'

urlpatterns = [
    path('', views.main_home, name='main_home'),
]

news/urls.py
from django.urls import path


from news.views import AllObjectView, ObjectDetail

app_name = 'news'
urlpatterns=[
    path('', AllObjectView.as_view(), name='main'),
    path('<int:pk>/', ObjectDetail.as_view(), name='object_detail'),
]

prof/urls.py
from django.urls import path

import prof
from prof.views import edit_profile, prof_create_view, ProfileUpdateView, ProfileDeleteView

app_name = 'prof'
urlpatterns=[
    path('prof/',  edit_profile, name='edit_pro'),
    path('prof_create/', prof_create_view, name='prof_create'),
    path('<int:pk>/update', ProfileUpdateView.as_view(), name='prof_update'),
    path('<int:pk>/delete', ProfileDeleteView.as_view(), name='prof_delete'),
]

report/urls.py
from django.urls import path

from report.views import ReportDeleteView

app_name = 'report'

urlpatterns = [
    path('<int:pk>/delete', ReportDeleteView.as_view(), name='report_delete'),
]

main/models.py
from django.db import models

# Create your models here.

news/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class AllObject(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='юзер')
    title = models.CharField(verbose_name='название', max_length=128)
    img = models.ImageField(verbose_name='картинка', upload_to='images/')
    des = models.TextField(verbose_name='текст')
    address = models.CharField(max_length=128, verbose_name='адресс')
    price = models.CharField(verbose_name='цена', max_length=32)
    max_human = models.IntegerField(verbose_name='макс. кол-во человек')
    date = models.DateTimeField('Дата публикации', auto_now_add=True)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Недвижимость'
        verbose_name_plural = 'Недвижимость'

prof/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bio = models.TextField()
    location = models.CharField(max_length=100)

report/models.py
from django.contrib.auth.models import User
from django.db import models

from news.models import AllObject


# Create your models here.
class Report(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='юзер')
    object_id = models.ForeignKey(AllObject, on_delete=models.CASCADE, verbose_name='ид')
    comment = models.TextField(verbose_name='текст')
    date = models.DateTimeField('Дата публикации', auto_now_add=True)

    def str(self):
        return self.comment

    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'

prof/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'location']

        widgets = {
            'user': forms.IntegerField(),
            'location': forms.TextInput(attrs={'class': 'form-control w-75', 'placeholder': 'Адрес'}),
            'bio': forms.Textarea(attrs={'class': 'form-control w-75', 'placeholder': 'Биография'}),
        }

report/forms.py
from django import forms

from report.models import Report


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = [

            'comment',
        ]

        widgets = {
            'comment': forms.Textarea(attrs={'class': 'form-control w-75', 'placeholder': 'Комментарий'}),
            'object_id': forms.Select(),
            'user_id': forms.IntegerField()
        }

main/views.py
from django.shortcuts import render


def main_home(request):
    return render(request, 'main/main.html')

news/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin

from news.models import AllObject
from report.forms import ReportForm


# Create your views here.
class AllObjectView(ListView):
    model = AllObject
    template_name = 'news/onject_list.html'
    context_object_name = 'objects'


class ObjectDetail(FormMixin, DetailView):
    model = AllObject
    template_name = 'news/object_detail.html'
    context_object_name = 'object'
    form_class = ReportForm
    success_url = '/prof/prof/'

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.object_id = self.get_object()
        self.object.user_id = self.request.user
        self.object.save()
        return super().form_valid(form)

prof/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import UpdateView, DeleteView

from report.models import Report
from .models import Profile
from .forms import ProfileForm

def edit_profile(request):

    current_user = request.user
    profile = Profile.objects.filter(user=current_user)
    your_report = Report.objects.filter(user_id=current_user)
        # Profile.objects.get(user=request.user.pk)



    return render(request,  'prof/prof.html', { 'your_report': your_report, 'profile':profile})



class ProfileUpdateView(UpdateView):
    model = Profile
    template_name = 'prof/prof_create.html'
    success_url = '/prof/prof/'
    form_class =  ProfileForm
def rootview(request):
    user = User
    return render(request, 'root.html', {'user' : user})



def prof_create_view(request):
    form = ProfileForm(request.POST)
    if form.is_valid():
        vacancies = form.save(commit=False)
        vacancies.user = request.user
        vacancies.save()

        return redirect('prof:edit_pro')

    else:
        form = ProfileForm()

    return render(request, 'prof/prof_create.html', {'form': form})


class ProfileDeleteView(DeleteView):
    model = Profile
    success_url = '/prof/prof/'
    template_name = 'prof/prof_delete.html'

report/views.py
from django.shortcuts import render
from django.views.generic import DeleteView

from report.models import Report


# Create your views here.
class ReportDeleteView(DeleteView):
    model = Report
    success_url = '/prof/prof/'
    template_name = 'prof/prof_delete.html'

main/templates/main/index.html
{% extends 'root.html' %}

main/templates/main/main.html
{% extends 'root.html' %}

<h1>главная</h1>

news/templates/news/object_detail.html
{% extends 'root.html' %}

{% block content %}
    <div class="card" style="width: 18rem;">
        <img src="{{ object.img.url }}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{ object.title }}</h5>
            <p class="card-text">{{ object.des }}</p>
            <p class="card-text">{{ object.date }}</p>
            <p class="card-text">{{ object.max_human }}</p>
            <p class="card-text">{{ object.price }}</p>
            <p class="card-text">{{ object.address }}</p>

        </div>
    </div>


    <form class="mt-3" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required><span class="ms-2">Примите условия и соглашения</span>
        <button type="submit" class="btn btn-success mt-2">OK</button>
    </form>
{% endblock %}

news/templates/news/onject_list.html
{% extends 'root.html' %}

{% block content %}
    {% for i in objects %}
        <div class="card" style="width: 18rem;">
            <img src="{{ i.img.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ i.title }}</h5>
                <p class="card-text">{{ i.price }}</p>
                <p class="card-text">{{ i.date }}</p>
                <a href="{% url 'object:object_detail' i.id %} " class="btn btn-primary w-100">detail</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

prof/templates/prof/prof.html
{% extends 'root.html' %}

{% block content %}

    {% for i in profile %}
        <div class="card">

            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <p>{{ i.user }}</p>
                    <p>{{ i.bio }}</p>
                    <p>{{ i.location }}</p>
                    <a class="btn btn-primary" href="{% url 'prof:prof_update' i.id %}">Изменить<a>
                        <a href="{% url 'prof:prof_delete' i.id %}" class="btn btn-danger ms-2">Удалить</a>
                </blockquote>
            </div>
        </div>
    {% endfor %}

    {% for i in your_report %}
        <div class="card mt-5">
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <p>{{ i.user_id }}</p>
                    <p>{{ i.object_id }}</p>
                    <p>{{ i.comment }}</p>
                    <a href="{% url 'report:report_delete' i.id %}" class="btn btn-danger">Отменить</a>
                    <footer class="blockquote-footer"><cite title="Source Title"><p>{{ i.date }}</p></cite>
                    </footer>
                </blockquote>
            </div>
        </div>
    {% endfor %}
{% endblock %}

prof/templates/prof/prof_create.html
{% extends 'root.html' %}

{% block content %}
    <form action="." method="post" enctype="multipart/form-data" class="p-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success mt-2">Готово</button>
    </form>
{% endblock %}

prof/templates/prof/prof_delete.html
{% extends 'root.html' %}

{% block content %}
<div class="d-flex justify-content-center align-items-center mt-5">
    <div style="margin: 2%;" class="d-flex justify-content-center align-items-center flex-column">
        <h3>Вы точно хотите удалить Профиль?</h3><br>
        <form method="post" style="width: 50%;" class="d-flex justify-content-center">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" style="font-size: 22px;">Подтвердить</button>
        </form>
    </div>
</div>
{% endblock %}

report/templates/report/report_delete.html
{% extends 'root.html' %}

{% block content %}
<div class="d-flex justify-content-center align-items-center mt-5">
    <div style="margin: 2%;" class="d-flex justify-content-center align-items-center flex-column">
        <h3>Вы точно хотите удалить заявку?</h3><br>
        <form method="post" style="width: 50%;" class="d-flex justify-content-center">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" style="font-size: 22px;">Подтвердить</button>
        </form>
    </div>
</div>
{% endblock %}

templates/root.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<style>
    .menu {
        height: 60px;
        width: 100%;
        background-color: #003366;
        display: flex;
        flex-direction: row;
        align-content: center;
        justify-content: space-evenly;
        align-items: center;

    }

    .logo h6 {
        color: white;
        font-size: 20px;
    }

    .men {
        display: flex;

    }

    .men a {
        text-decoration: none;
        color: white;
        margin: 0px 10px 0px 10px;
        font-size: 18px;
    }

</style>
<div class="menu">
    <div class="logo"><h6>Сервис для аренды недвижимости </h6></div>
    <div class="men">
        <a href="{% url 'main:main' %}">Главная</a>
        <a href="{% url 'object:main' %}">Просмотр жилья</a>
        <a href="{% url 'prof:edit_pro' %}">Мой профиль</a>
{#        <a href="{% url 'prof:prof_create' %}">Создать профиль</a>#}
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">Выйти</a>
        {% else %}
            <a href="{% url 'auth:sign-up' %}">Регистрация</a>
            <a href="{% url 'auth:login' %}">Войти</a>
        {% endif %}
    </div>
</div>
{% block content %}
{% endblock %}
</body>
</html>